[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  CI = "false"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  publish = "build"
  functions = "netlify/functions"
  functionsPort = 9999

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200